"""
Core configuration package.
"""
from backend.app.core.config import (
    ROOT_DIR, BACKEND_DIR, FRONTEND_DIR, APP_DIR,
    TEMPLATES_DIR, STATIC_DIR, DATA_DIR, MODELS_DIR,
    RAW_DATA_PATH, SAMPLE_DATA_PATH, PROCESSED_DATA_PATH,
    PROPHET_MODEL_PATH, METADATA_PATH, ML_FORECAST_MODEL_PATH, SARIMA_MODEL_PATH,
    APP_HOST, APP_PORT, DEBUG
)
